---
name: deploy_terraform_to_linode
on:
  pull_request:
  release:
    types: [released]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint_and_format_pr:
    name: lint_and_format_pr
    runs-on: ubuntu-latest
    env:
      vault_endpoint: https://vault-cluster.vault.f7138e83-ed41-4970-8209-2d60a69c6a0f.aws.hashicorp.cloud:8200
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ env.vault_endpoint}}
          tlsSkipVerify: true
          method: token
          namespace: admin/yoyodynecorp
          token: ${{ secrets.VAULT_API_TOKEN }}
          secrets: |
            secret/data/github_action_linode_terraform TF_VAR_LINODE_KUBERNETES_API_TOKEN ;
            secret/data/github_action_linode_terraform CONSUL_HTTP_TOKEN
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init -lock=false
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Plan
        run: terraform plan -lock=false -input=false -var-file="terraform.tfvars"

  deploy_terraform_to_linode:
    needs: lint_and_format_pr
    name: deploy_terraform_to_linode
    if: github.event_name == 'release' && github.event.action == 'released'
    runs-on: macos-12
    env:
      vault_endpoint: https://vault-cluster.vault.f7138e83-ed41-4970-8209-2d60a69c6a0f.aws.hashicorp.cloud:8200
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ env.vault_endpoint}}
          tlsSkipVerify: true
          method: token
          namespace: admin/yoyodynecorp
          token: ${{ secrets.VAULT_API_TOKEN }}
          secrets: |
            secret/data/github_action_linode_terraform TF_VAR_LINODE_KUBERNETES_API_TOKEN ;
            secret/data/github_action_linode_terraform CONSUL_HTTP_TOKEN
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init -lock=false
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Plan
        run: terraform plan -lock=false -input=false -var-file="terraform.tfvars"
      - name: Terraform Apply
        run: terraform apply -lock=false -auto-approve -input=false -var-file="terraform.tfvars"